// views/nillion-file-store/src/Plugin.tsx
import styles from "./Plugin.module.css";
import { PerspectiveProxy } from "@coasys/ad4m";
import FileView from "./components/FileView";
import { AgentClient } from "@coasys/ad4m/lib/src/agent/AgentClient";

type Props = {
  agent: AgentClient;
  perspective: PerspectiveProxy;
  source: string;
};

export default function Plugin({ agent, perspective, source }: Props) {
  if (!perspective?.uuid || !agent) return "No perspective or agent client";

  return (
    <div className={styles.appContainer}>
      <FileView
        perspective={perspective}
        source={source}
        agent={agent}
      ></FileView>
    </div>
  );
}

// packages/create/templates/vue/src/Plugin.vue
<template>
  <div v-if="hasPerspective" :class="styles.appContainer">
    <TodoView :perspective="perspective" :source="source" />
  </div>

  <template v-else> No perspective or agent client </template>
</template>

<script setup lang="ts">
import styles from './Plugin.module.css';
import type { PerspectiveProxy } from '@coasys/ad4m';
import type { AgentClient } from '@coasys/ad4m';
import { computed } from 'vue';
import TodoView from './components/TodoView.vue';

type Props = Partial<{
  agent: AgentClient;
  perspective: PerspectiveProxy;
  source: string;
}>;

const { perspective, agent, source } = defineProps<Props>();

const hasPerspective = computed(() => perspective?.uuid != null && agent != null);
</script>
