// app/src/components/avatar/Avatar.vue
<template>
  <j-avatar
    :slot="slot"
    :initials="initials"
    :hash="did"
    :src="realSrc || src"
    :size="size"
    :online="online"
  ></j-avatar>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { getImage } from "@fluxapp/utils";
export default defineComponent({
  props: {
    did: String,
    url: String,
    src: String,
    size: {
      type: String,
      default: "md",
    },
    slot: String,
    online: Boolean,
    initials: String,
  },
  data() {
    return { realSrc: null as null | string, loading: false };
  },
  watch: {
    url: {
      handler(url: string) {
        if (url) {
          if (url.includes("base64")) {
            this.realSrc = url;
          } else {
            this.getProfileImage(url);
          }
        } else {
          this.realSrc = null;
        }
      },
      immediate: true,
    },
  },
  methods: {
    async getProfileImage(url: string) {
      try {
        this.loading = true;
        const src = await getImage(url);
        this.realSrc = src || null;
      } finally {
        this.loading = false;
      }
    },
  },
});
</script>

<style scoped>
j-avatar::part(base) {
  aspect-ratio: 1/1;
}
</style>

// packages/comment-section/src/Components/Avatar/index.tsx
import { getImage } from "@fluxapp/utils";
import { useEffect, useState } from "preact/hooks";

type AvatarProps = {
  did: string;
  url?: string;
  src?: string;
  style?: any;
  onClick?: (event: any) => void;
  size?: "" | "xxs" | "xs" | "sm" | "lg" | "xl" | "xxl";
};

export default function Avatar({
  did,
  src,
  url,
  style,
  onClick,
  size = "",
}: AvatarProps) {
  const [loading, setLoading] = useState(false);
  const [img, setImage] = useState(null);

  async function fetchImage(imageUrl) {
    try {
      setLoading(true);
      const image = await getImage(imageUrl);
      setImage(image);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    if (url) {
      fetchImage(url);
    }
  }, [did, url]);

  return (
    <j-avatar
      style={{ ...style, cursor: onClick ? "pointer" : "default" }}
      hash={did}
      src={img || src}
      onClick={(e: any) => onClick && onClick(e)}
      size={size}
    ></j-avatar>
  );
}
