// views/webrtc-debug/src/components/Settings/VoiceVideo/VoiceVideo.tsx
import { WebRTC } from "../../../hooks/useWebrtc";
import { Me } from "utils/api";
import { getForVersion } from "utils/helpers";
import Select from "../../Select";

type Props = {
  webRTC: WebRTC;
  currentUser?: Me;
};

export default function VoiceVideo({ webRTC }: Props) {
  const videoTrack = webRTC.localStream
    ?.getTracks()
    ?.find((track) => track.kind === "video");

  const audioTrack = webRTC.localStream
    ?.getTracks()
    ?.find((track) => track.kind === "audio");

  const selectedVideoDeviceId =
    typeof webRTC.settings.video !== "boolean" &&
    webRTC.settings.video?.deviceId
      ? webRTC.settings.video?.deviceId
      : videoTrack?.getSettings().deviceId || getForVersion("cameraDeviceId");

  const selectedAudioDeviceId =
    typeof webRTC.settings.audio !== "boolean" &&
    webRTC.settings.audio?.deviceId
      ? webRTC.settings.audio?.deviceId
      : audioTrack?.getSettings().deviceId || getForVersion("audioDeviceId");

  const videoDevices = webRTC?.devices?.filter((d) => d.kind === "videoinput");
  const audioDevices = webRTC?.devices?.filter((d) => d.kind === "audioinput");

  return (
    <div>
      <h3>Voice & Video settings</h3>
      <j-box pt={300}>
        <Select
          name="video-device"
          label="Video input device"
          placeholder="Select device"
          selected={selectedVideoDeviceId}
          options={videoDevices.map((v) => ({
            text: v.label,
            value: v.deviceId,
          }))}
          onChange={(e) => {
            webRTC.onChangeCamera(e.target.value);
          }}
        />
      </j-box>

      <j-box pt={500}>
        <Select
          name="audio-device"
          label="Audio input device"
          placeholder="Select device"
          selected={selectedAudioDeviceId}
          options={audioDevices.map((v) => ({
            text: v.label,
            value: v.deviceId,
          }))}
          onChange={(e) => {
            webRTC.onChangeAudio(e.target.value);
          }}
        />
      </j-box>
    </div>
  );
}

// app/src/components/webrtc-settings-modal/VoiceVideo.vue
<template>
  <div>
    <h3>Voice & Video settings</h3>
    <j-box :pt="300">
      <j-flex j="end" a="center" gap="200" direction="row">
        <Select
          name="video-device"
          label="Video input device"
          placeholder="Select device"
          :selected="activeCameraId || ''"
          :options="videoDeviceOptions"
          @change="(e: any) => mediaDevicesStore.switchCamera(e.target.value)"
        />

        <!-- <j-box v-if="!webRTC.videoPermissionGranted" :pt="600">
          <j-button @click="() => webRTC.onToggleCamera(true)" size="sm"> Allow permission </j-button>
        </j-box> -->
      </j-flex>
    </j-box>

    <j-box :pt="500">
      <Select
        name="audio-device"
        label="Audio input device"
        placeholder="Select device"
        :selected="activeMicrophoneId || ''"
        :options="audioDeviceOptions"
        @change="(e: any) => mediaDevicesStore.switchMicrophone(e.target.value)"
      />
    </j-box>
  </div>
</template>

<script setup lang="ts">
import { useMediaDevicesStore } from "@/stores/mediaDevicesStore";
import { storeToRefs } from "pinia";
import { computed } from "vue";
import Select from "./Select.vue";

const mediaDevicesStore = useMediaDevicesStore();

const { cameras, microphones, activeCameraId, activeMicrophoneId } = storeToRefs(mediaDevicesStore);

const videoDeviceOptions = computed(() => cameras.value.map((v) => ({ text: v.label, value: v.deviceId })));
const audioDeviceOptions = computed(() => microphones.value.map((v) => ({ text: v.label, value: v.deviceId })));
</script>
