// views/chat-view/src/components/Avatar/Avatar.tsx
import { getImage } from "@fluxapp/utils";
import { useEffect, useState } from "preact/hooks";

type AvatarProps = {
  size: "" | "xxs" | "xs" | "md" | "sm" | "lg" | "xl" | "xxl";
  profileAddress?: string;
  hash?: string;
}

export default function Avatar({size = 'md', hash, profileAddress}: AvatarProps) {
  const [image, setImage] = useState<string>();

  useEffect(() => {
    if (typeof profileAddress === "string") {
      if (profileAddress.includes("base64")) {
        setImage(profileAddress);
      } else {
        getProfileImage(profileAddress);
      }
    } else {
      setImage(null)
    }
  }, [profileAddress])

  async function getProfileImage(url: string) {
    try {
      const src = await getImage(url);
      setImage(src)
    } finally {
    }
  }

  return (
    <j-avatar
      size={size}
      src={image}
      hash={hash}
    ></j-avatar>
  )
}

// app/src/components/avatar/Avatar.vue
<template>
  <j-avatar
    :slot="slot"
    :initials="initials"
    :hash="did"
    :src="realSrc || src"
    :size="size"
    :online="online"
  ></j-avatar>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { getImage } from "@fluxapp/utils";
export default defineComponent({
  props: {
    did: String,
    url: String,
    src: String,
    size: {
      type: String,
      default: "md",
    },
    slot: String,
    online: Boolean,
    initials: String,
  },
  data() {
    return { realSrc: null as null | string, loading: false };
  },
  watch: {
    url: {
      handler(url: any) {
        if (typeof url === "string") {
          if (url.includes("base64")) {
            this.realSrc = url;
          } else {
            this.getProfileImage(url);
          }
        } else {
          this.realSrc = null;
        }
      },
      immediate: true,
    },
  },
  methods: {
    async getProfileImage(url: string) {
      try {
        this.loading = true;
        const src = await getImage(url);
        this.realSrc = src || null;
      } finally {
        this.loading = false;
      }
    },
  },
});
</script>

<style scoped>
j-avatar::part(base) {
  aspect-ratio: 1/1;
}
</style>
