// packages/flux/src/components/avatar/Avatar.vue
<template>
  <j-skeleton
    :slot="slot"
    variant="circle"
    :height="size"
    :width="size"
    v-if="loading"
  ></j-skeleton>
  <j-avatar
    v-else
    :slot="slot"
    :initials="initials"
    :hash="did"
    :src="realSrc"
    :size="size"
    :online="online"
  ></j-avatar>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { getImage } from "utils/api/getProfile";
import Skeleton from "../skeleton/Skeleton.vue";
export default defineComponent({
  props: {
    did: String,
    url: String,
    src: String,
    size: {
      type: String,
      default: "md",
    },
    slot: String,
    online: Boolean,
    initials: String,
  },
  data() {
    return { realSrc: null as null | string, loading: false };
  },
  watch: {
    url: {
      handler(url: string) {
        if (url) {
          this.getProfileImage(url);
        } else {
          this.realSrc = null;
        }
      },
      immediate: true,
    },
  },
  methods: {
    async getProfileImage(url: string) {
      try {
        this.loading = true;
        const src = await getImage(url);
        this.realSrc = src || null;
      } finally {
        this.loading = false;
      }
    },
  },
  components: { Skeleton },
});
</script>

<style scoped>
j-avatar::part(base) {
  aspect-ratio: 1/1;
}
</style>

// packages/chat-view/src/components/Avatar/index.tsx
import { getImage } from "utils/api/getProfile";
import { useEffect, useState } from "preact/hooks";

type AvatarProps = {
  did: string;
  url: string;
  style?: any;
  onProfileClick?: (did: string) => void;
  size?: "xs" | "sm" | "md" | "lg";
};

export default function Avatar({
  did,
  url,
  style,
  onProfileClick = () => {},
  size = "md",
}: AvatarProps) {
  const [loading, setLoading] = useState(false);
  const [img, setImage] = useState(null);

  async function fetchImage(imageUrl) {
    try {
      setLoading(true);
      const image = await getImage(imageUrl);
      setImage(image);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    if (url) {
      fetchImage(url);
    }
  }, [did, url]);

  if (loading)
    return (
      <j-skeleton
        variant="circle"
        style={style}
        onClick={() => onProfileClick(did)}
        height={size}
        width={size}
      ></j-skeleton>
    );

  return (
    <j-avatar
      style={style}
      src={img}
      hash={did}
      onClick={() => onProfileClick(did)}
      size={size}
    ></j-avatar>
  );
}
