// packages/chat-view/src/components/Avatar/index.tsx
import getProfile, { getImage } from "utils/api/getProfile";
import { useEffect, useMemo, useState } from "preact/hooks";
import { Profile } from "utils/types";

type AvatarProps = {
  did: string;
  url: string;
  style: any;
  onProfileClick?: (did: string) => void;
  size?: "xs" | "sm" | "md" | "lg";
};

export default function Avatar({
  did,
  url,
  style,
  onProfileClick = () => {},
  size = "md",
}: AvatarProps) {
  const [img, setImage] = useState(null);

  useEffect(() => {
    if (url) {
      getImage(url)
        .then((data) => setImage(data))
        .catch((e) => console.error(e));
    }
  }, [did, url]);

  return (
    <j-avatar
      style={style}
      src={img}
      hash={did}
      onClick={() => onProfileClick(did)}
      size={size}
    ></j-avatar>
  );
}

// src/components/avatar/Avatar.vue
<template>
  <j-avatar
    :slot="slot"
    :initials="initials"
    :hash="did"
    :src="src"
    :size="size"
    :online="online"
  ></j-avatar>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { getImage } from "@/utils/profileHelpers";
export default defineComponent({
  props: {
    did: String,
    url: String,
    size: String,
    slot: String,
    online: Boolean,
    initials: String,
  },
  data() {
    return { src: "" };
  },
  watch: {
    url: {
      async handler(url) {
        if (url) {
          this.src = await getImage(url);
        } else {
          this.src = "";
        }
      },
      immediate: true,
    },
  },
});
</script>
