// app/src/components/conversation/percentage-ring/PercentageRing.vue
<template>
  <div class="percentage-ring-wrapper" :style="{ width: `${ringSize}px`, height: `${ringSize}px` }">
    <svg>
      <defs>
        <linearGradient id="gradient" transform="rotate(180)">
          <stop offset="0%" stop-color="var(--j-color-primary-400)" />
          <stop offset="100%" stop-color="var(--j-color-primary-600)" />
        </linearGradient>
      </defs>
      <circle
        cx="50%"
        cy="50%"
        :r="radius"
        stroke="url(#gradient)"
        :stroke-width="strokeWidth"
        :stroke-dasharray="`${(circumference * score) / 100} ${circumference}`"
      />
    </svg>
    <p :style="{ fontSize: `${fontSize}px` }">{{ score.toFixed(1) }}%</p>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';

const props = defineProps<{ ringSize: number; fontSize: number; score: number }>();

const radius = computed(() => props.ringSize / 2 - 10);
const circumference = computed(() => 2 * Math.PI * radius.value);
const strokeWidth = computed(() => props.ringSize / 10);
</script>

<style lang="scss" scoped>
.percentage-ring-wrapper {
  position: relative;
  display: flex;
  justify-content: center;
  align-items: center;
  flex-shrink: 0;

  svg {
    width: inherit;
    height: inherit;
    transform: rotate(-90deg);

    circle {
      fill: transparent;
      stroke-linecap: round;
    }
  }

  p {
    position: absolute;
    margin: 0;
  }
}
</style>

// views/synergy-demo-view/src/components/PercentageRing/PercentageRing.tsx
import styles from './PercentageRing.module.scss';

type Props = { ringSize: number; fontSize: number; score: number };

export default function PercentageRing({ ringSize, fontSize, score }: Props) {
  const radius = ringSize / 2 - 10;
  const circumference = 2 * Math.PI * radius;
  return (
    <div className={styles.wrapper} style={{ width: ringSize, height: ringSize }}>
      <svg>
        <defs>
          <linearGradient id="gradient" transform="rotate(180)">
            <stop offset="0%" stop-color="var(--j-color-primary-400)" />
            <stop offset="100%" stop-color="var(--j-color-primary-600)" />
          </linearGradient>
        </defs>
        <circle
          cx="50%"
          cy="50%"
          r={radius}
          stroke="url(#gradient)"
          strokeWidth={ringSize / 10}
          strokeDasharray={`${(circumference * score) / 100} ${circumference}`}
        />
      </svg>
      <p style={{ fontSize }}>{score.toFixed(1)}%</p>
    </div>
  );
}
