// app/src/components/synergy/avatar/Avatar.vue
<template>
  <j-flex gap="300" a="center" :style="style">
    <div class="avatar-image">
      <j-avatar :size="size" :src="profile.profileThumbnailPicture || null" :hash="did" />
    </div>
    <j-text v-if="showName" nomargin>{{ profile.username }}</j-text>
  </j-flex>
</template>

<script setup lang="ts">
import { getCachedAgentProfile } from "@/utils/userProfileCache";
import { Profile } from "@coasys/flux-types";
import { onMounted, ref } from "vue";

interface Props {
  did: string;
  size?: "sm" | "xs" | "lg" | "xl" | "xxs" | "xxl";
  showName?: boolean;
  style?: any;
}

const props = withDefaults(defineProps<Props>(), {
  size: "sm",
  showName: false,
});

const profile = ref<Partial<Profile>>({});

onMounted(async () => {
  try {
    profile.value = await getCachedAgentProfile(props.did);
  } catch (error) {
    console.error("Error loading profile:", error);
  }
});
</script>

<style lang="scss" scoped>
.avatar-image {
  background-color: var(--j-color-ui-100);
  box-shadow: 0 0 0 1px var(--j-color-ui-200);
  border-radius: 50%;
  width: var(--j-size-sm);
  height: var(--j-size-sm);
  z-index: 1;
}
</style>

// views/poll-view/src/components/Avatar/Avatar.tsx
import { Profile } from '@coasys/flux-types';
import { useEffect, useState } from 'preact/hooks';
import styles from './Avatar.module.scss';

type Props = {
  did: string;
  size?: 'sm' | 'xs' | 'lg' | 'xl' | 'xxs' | 'xxl';
  showName?: boolean;
  style?: any;
  getProfile: (did: string) => Promise<Profile>;
};

export default function Avatar({ did, size = 'sm', showName = false, style, getProfile }: Props) {
  const [profile, setProfile] = useState<Partial<Profile>>({});

  async function getProfileData() {
    const profile = await getProfile(did);
    setProfile(profile);
  }

  useEffect(() => {
    if (getProfile) getProfileData();
  }, [getProfile]);

  return (
    <j-flex gap="300" a="center" style={style}>
      <div className={styles.image} style={{ height: size === 'xs' ? 28 : 36 }}>
        <j-avatar size={size} src={profile.profileThumbnailPicture || null} hash={did} />
      </div>
      {showName && <j-text nomargin>{profile.username}</j-text>}
    </j-flex>
  );
}
